# Generated by Django 5.2.13 on 2026-04-13 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='imafe_file',
            new_name='image_file',
        ),
    ]
